# Generated by Django 2.1.4 on 2018-12-05 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=126)),
                ('point', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min', models.IntegerField(default=0, unique=True)),
                ('max', models.IntegerField(default=0, unique=True)),
                ('type', models.CharField(max_length=64)),
                ('descriptions', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchandise_type', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=128)),
                ('available_count', models.IntegerField()),
                ('more_info', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_order_list', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_order_list', to='QuanLyNhaSach.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderBillDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_detail', to='QuanLyNhaSach.OrderBill')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_order_detail_list', to='QuanLyNhaSach.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('min', models.IntegerField(default=0, unique=True)),
                ('max', models.IntegerField(default=0, unique=True)),
                ('date_expired', models.DateField()),
                ('money_discount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('paid', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferInDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_detail', to='QuanLyNhaSach.StockTransferIn')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_detail_list', to='QuanLyNhaSach.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferOutDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_detail', to='QuanLyNhaSach.StockTransferOut')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_detail_list', to='QuanLyNhaSach.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cooperation_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='stocktransferout',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Store'),
        ),
        migrations.AddField(
            model_name='stocktransferin',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_list', to='QuanLyNhaSach.Store'),
        ),
        migrations.AddField(
            model_name='stocktransferin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_list', to='QuanLyNhaSach.Supplier'),
        ),
        migrations.AddField(
            model_name='orderbill',
            name='receive_at',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_order_list', to='QuanLyNhaSach.Store'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyNhaSach.MerchandiseType'),
        ),
    ]
