# Generated by Django 2.1 on 2019-11-11 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=126)),
                ('point', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extend_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('min', models.IntegerField(default=0, unique=True)),
                ('max', models.IntegerField(default=0, unique=True)),
                ('type', models.CharField(max_length=64, unique=True)),
                ('descriptions', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('merchandise_type', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('name', models.CharField(max_length=128)),
                ('available_count', models.IntegerField(default=0)),
                ('more_info', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_for', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('type_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.TextField()),
                ('display_name', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16)),
                ('min', models.IntegerField(default=0)),
                ('date_expired', models.DateField()),
                ('money_discount', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('paid', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferInDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=1)),
                ('inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_detail', to='QuanLyNhaSach.StockTransferIn')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_detail_list', to='QuanLyNhaSach.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Customer')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Promotion')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferOutDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('price', models.IntegerField(default=0)),
                ('inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_detail', to='QuanLyNhaSach.StockTransferOut')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_detail_list', to='QuanLyNhaSach.Merchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('cooperation_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='stocktransferin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_in_list', to='QuanLyNhaSach.Supplier'),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QuanLyNhaSach.MerchandiseType'),
        ),
    ]
