# Generated by Django 2.1.4 on 2018-12-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferout',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Promotion'),
        ),
    ]
