# Generated by Django 2.1.4 on 2018-12-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0002_stocktransferout_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='more_info',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='RXRJUZEF', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
