# Generated by Django 2.1 on 2019-11-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0002_auto_20191114_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferout',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransferout',
            name='channel',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='picture',
            field=models.CharField(default='', max_length=512),
        ),
    ]
