# Generated by Django 2.1.4 on 2018-12-10 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0003_auto_20181208_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='merchandise_type',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='IFABABIG', max_length=16, unique=True),
        ),
    ]
