# Generated by Django 2.1.4 on 2018-12-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0004_auto_20181210_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='ZRIQINPG', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransferin',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
