# Generated by Django 2.1.4 on 2018-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0005_auto_20181210_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='APSBFPOW', max_length=16, unique=True),
        ),
    ]
