# Generated by Django 2.1.4 on 2018-12-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0006_auto_20181210_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='YWKEEZAS', max_length=16, unique=True),
        ),
    ]
