# Generated by Django 2.1.4 on 2018-12-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0008_auto_20181211_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbill',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderbill',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderbill',
            name='receive_at',
        ),
        migrations.RemoveField(
            model_name='orderbilldetail',
            name='inside',
        ),
        migrations.RemoveField(
            model_name='orderbilldetail',
            name='unit',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='WNRAYBXO', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='stocktransferout',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfer_out_list', to='QuanLyNhaSach.Promotion'),
        ),
        migrations.DeleteModel(
            name='OrderBill',
        ),
        migrations.DeleteModel(
            name='OrderBillDetail',
        ),
    ]
