# Generated by Django 2.1.4 on 2018-12-12 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0009_auto_20181211_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandisetype',
            name='type_for',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='BWJAISDJ', max_length=16, unique=True),
        ),
    ]
