# Generated by Django 2.1.4 on 2018-12-13 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0010_auto_20181212_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='SFDYYARA', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cooperation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 22, 40, 40, 306984)),
        ),
    ]
