# Generated by Django 2.1.4 on 2018-12-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0011_auto_20181213_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='LSULZSZD', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cooperation_date',
            field=models.DateField(),
        ),
    ]
