# Generated by Django 2.1.4 on 2018-12-13 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0012_auto_20181213_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='FDCGVSSC', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cooperation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 23, 8, 20, 185821)),
        ),
    ]
