# Generated by Django 2.1.4 on 2018-12-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0014_auto_20181213_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='SSKWFDZN', max_length=16, unique=True),
        ),
    ]
