# Generated by Django 2.1.4 on 2018-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0015_auto_20181213_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='KDXJCKOF', max_length=16, unique=True),
        ),
    ]
