# Generated by Django 2.1.4 on 2018-12-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0016_auto_20181214_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(default='OIIZYXKQ', max_length=16, unique=True),
        ),
    ]
