# Generated by Django 2.1 on 2018-12-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0019_auto_20181214_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransferin',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stocktransferout',
            name='store',
        ),
        migrations.AlterField(
            model_name='customertype',
            name='type',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
