# Generated by Django 2.1 on 2018-12-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuanLyNhaSach', '0020_auto_20181216_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='max',
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
